- src/components/Header/index.tsx
- src/components/Input/index.tsx
- src/components/Input/input.module.scss
- src/components/Modal/index.tsx
- src/components/Select/index.tsx
- src/components/Select/select.module.scss
- src/pages/Login/index.tsx
- src/pages/SignUp/components/SignUp/index.tsx
- src/pages/SignUp/components/SignUp/signUp.module.scss
- src/pages/components/RegisterContent/SelectAbility.js
- src/pages/components/RegisterContent/SelectType.js
- src/pages/components/RegisterContent/index.tsx
- src/pages/components/RegisterContent/registerContent.module.scss
> feat: cadastro conteudo professor

- src/_App.tsx
- src/pages/components/ContentCard/contentCard.module.scss
- src/pages/components/ContentCard/index.tsx
Criação da estilização do card de conteúdo
>Quando passar o mouse por cima do card , deve trocar de cor
- [X ] Confirmo que testei minhas alterações
- [ X] Meu código segue o padrão atual do projeto
- [ X] Eu fiz uma autoavaliação do meu próprio código
- [ X] Minhas alterações não geram novos **warning** ou **erros**
> feat: Criação do card de conteúdo

- package.json
- src/pages/Login/index.tsx
- src/pages/SignUp/FormStep2/index.tsx
- src/pages/SignUp/FormStudent/index.tsx
- yarn.lock
Foi adicionado o axios ao projeto e feita integrações de cadastro e login com a API do back-end.
- Quando o usuário realizar o login deverá ser retornado um token jwt;
- Quando o estudante ou professor fizer um cadastro, esses dados devem ser armazenados no banco de dados.
> feat: add axios api login/cadastro integration

- src/pages/components/RegisterQuestion/index.tsx
- src/pages/components/RegisterQuestion/registerQuestion.module.scss
> Criação modal de cadastro de questões
> tela estatica para cadastrar questões
> feat: Modal para cadastrar uma questão

- src/pages/components/DeleteTopic/deleteTopic.module.scss
- src/pages/components/DeleteTopic/index.tsx
> Criação modal de delete tópico
> Modal estático para deletar um topico
> Feat: modal delete topico

- src/components/Input/index.tsx
- src/components/Select/select.module.scss
- src/pages/components/RegisterContent/index.tsx
- src/pages/components/SelectedTopic/index.tsx
- src/pages/components/SelectedTopic/selectedTopics.module.scss
- src/styles/sass/_variables.scss
> Criação do modal de topico selecionado
> Input dinâmico, ao clicar em adicionar surge um novo campo de input
> feat modal de topico selecionado

- src/pages/components/CardTopic/cardTopic.module.scss
- src/pages/components/CardTopic/index.tsx
> Criação do componente, carde de tópico
> componente estático
> feat: componente card topico

- src/components/Reading/index.tsx
- src/components/Reading/reading.module.scss
> Feito a "Página" de ler conteúdo: Componentização e estilização
- [ X] Confirmo que testei minhas alterações
- [ X] Meu código segue o padrão atual do projeto
- [ X] Eu fiz uma autoavaliação do meu próprio código
- [ X] Minhas alterações não geram novos **warning** ou **erros**
> feat/reading:Ver conteúdo

- src/components/ContentCard/index.tsx
- src/pages/Teacher/DeleteContent/index.tsx
- src/pages/Teacher/Home/index.tsx
- src/pages/Teacher/RegisterContent/index.tsx
- src/pages/Teacher/UpdateContent/UpdateSuccess/index.tsx
- src/pages/Teacher/UpdateContent/index.tsx
- src/services/post.service.js
> feat: integrando update e delete

- src/components/CardLikert/ImageItems.js
- src/components/CardLikert/cardLikert.module.scss
- src/components/CardLikert/index.tsx
- src/components/SearchBar/index.tsx
- src/pages/Student/index.tsx
- src/pages/Student/student.module.scss
- src/pages/Teacher/Content/content.module.scss
- src/pages/Teacher/Home/home.module.scss
- src/pages/Teacher/Home/index.tsx
> Criação do componente card likert e correções  nas paginas estudante e professor 
>
> feat componente likert, correções

- src/pages/Home/components/Feedbacks/index.tsx
- src/pages/Home/components/FooterHome/index.tsx
- src/pages/Home/components/Intro/index.tsx
> Adição de textos a página de home
- [ X] Confirmo que testei minhas alterações
- [ X] Meu código segue o padrão atual do projeto
- [ X] Eu fiz uma autoavaliação do meu próprio código
- [ X] Minhas alterações não geram novos **warning** ou **erros**
> feat/textHome: Adição de textos para a página de home

- package.json
- src/_App.tsx
- src/components/CardLikert/index.tsx
- src/components/ContentCard/index.tsx
- src/components/Reading/index.tsx
- src/components/Sidebar/index.tsx
- src/components/VideoClass/index.tsx
- src/pages/SignUp/FormStep2/index.tsx
- src/pages/SignUp/FormStudent/index.tsx
- src/pages/Student/Forum/CardTopic/cardTopic.module.scss
- src/pages/Student/Forum/CardTopic/index.tsx
- src/pages/Student/Forum/DeleteTopic/index.tsx
- src/pages/Student/Forum/RegisterTopic/index.tsx
- src/pages/Student/Forum/SelectedTopic/index.tsx
- src/pages/Student/Forum/Topics/index.tsx
- src/pages/Student/Forum/UpdateTopic/index.tsx
- src/pages/Student/Home/index.tsx
- src/pages/Student/index.tsx
- src/pages/Teacher/Content/index.tsx
- src/pages/Teacher/DeleteContent/index.tsx
- src/pages/Teacher/Home/index.tsx
- src/pages/Teacher/Overview/Card/index.tsx
- src/pages/Teacher/RegisterContent/index.tsx
- src/pages/Teacher/UpdateContent/index.tsx
- src/pages/Teacher/index.tsx
- src/services/post.service.js
> feat: integrações com o back end e ajustes

- src/components/ContentCard/contentCard.module.scss
- src/components/ContentCard/index.tsx
- src/components/SearchBar/index.tsx
- src/components/Sidebar/Perfil/perfil.module.scss
- src/pages/Student/Forum/CardTopic/index.tsx
- src/pages/Student/Home/index.tsx
- src/pages/Teacher/Content/index.tsx
- src/pages/Teacher/Home/home.module.scss
> Barra de pesquisa funcional, e correções na estilização dos cards de conteúdos
>barra de pesquisa; deve ser pesquisado pelo titulo do conteúdo, aceitando letras maiusculas e minusculas, também reconhece qualquer parte do corpo do texto.
obs: atenção quanto aos acento, pois o filtro não reconhece os sinais gráficos.
> fix; searchBar funcional finalizado, correção dos cards de conteudo

- src/components/CardLikert/index.tsx
- src/components/Sidebar/MenuItemsStudent.js
- src/components/Sidebar/Perfil/index.tsx
- src/components/Sidebar/index.tsx
- src/pages/Login/index.tsx
- src/pages/SignUp/FormStep1/formStep1.module.scss
- src/pages/SignUp/FormStep1/index.tsx
- src/pages/SignUp/FormStep2/formStep2.module.scss
- src/pages/SignUp/FormStep2/index.tsx
- src/pages/SignUp/FormStudent/formStudent.module.scss
- src/pages/SignUp/FormStudent/index.tsx
- src/pages/Student/Forum/CardTopic/index.tsx
- src/pages/Student/Forum/DeleteTopic/index.tsx
- src/pages/Student/Forum/RegisterTopic/index.tsx
- src/pages/Student/Forum/RegisterTopic/registerQuestion.module.scss
- src/pages/Student/Forum/Topics/index.tsx
- src/pages/Student/Forum/UpdateTopic/index.tsx
- src/pages/Student/Forum/UpdateTopic/updateTopic.module.scss
- src/pages/Student/Forum/index.tsx
- src/pages/Student/Home/index.tsx
- src/pages/Student/index.tsx
- src/pages/Teacher/Content/index.tsx
- src/pages/Teacher/Home/index.tsx
- src/pages/Teacher/index.tsx
- src/services/post.service.js
- src/utils/contexts/FormContext.tsx
- Adicionando validações nos formulários de cadastro (estudante e professor);
- Validação no cadastro e update do tópico
> feat: validação dos formulários estudante, professor e tópicos

- src/pages/Student/Forum/CardTopic/cardTopic.module.scss
- src/pages/Student/Forum/SelectedTopic/index.tsx
- src/pages/Student/Forum/SelectedTopic/selectedTopics.module.scss
- src/pages/Student/Forum/Topics/index.tsx
- src/pages/Student/Forum/index.tsx
- src/services/post.service.js
> fix: ajuste no forum e integração da thread

- src/components/SearchBar/index.tsx
- src/pages/Student/Forum/SelectedTopic/index.tsx
- src/pages/Student/Forum/SelectedTopic/selectedTopics.module.scss
> fix: css correcao

- src/pages/Teacher/RegisterContent/index.tsx
- src/pages/Teacher/RegisterContent/registerContent.module.scss
> feat: validação básica no registerContent

- src/_App.tsx
- src/pages/Teacher/RegisterContent/index.tsx
- src/pages/Teacher/UpdateContent/index.tsx
> feat: validação básica no updateContent

- src/pages/Student/Forum/CardTopic/index.tsx
- src/pages/Student/Forum/RegisterTopic/registerQuestion.module.scss
- src/pages/Student/Forum/SelectedTopic/index.tsx
- src/pages/Student/Forum/SelectedTopic/selectedTopics.module.scss
- src/pages/Student/Forum/Topics/index.tsx
> fix: answers style

- src/_App.tsx
- src/pages/Login/index.tsx
> feat: validaçao de redirecionamento de professor ou usuario
